<?php 
$country_mobile_lengths = [
    '1'   => ['name' => 'United States/Canada', 'min' => 10, 'max' => 10],
    '7'   => ['name' => 'Russia/Kazakhstan', 'min' => 10, 'max' => 10],
    '20'  => ['name' => 'Egypt', 'min' => 10, 'max' => 10],
    '27'  => ['name' => 'South Africa', 'min' => 9, 'max' => 9],
    '30'  => ['name' => 'Greece', 'min' => 10, 'max' => 10],
    '31'  => ['name' => 'Netherlands', 'min' => 9, 'max' => 9],
    '32'  => ['name' => 'Belgium', 'min' => 8, 'max' => 9],
    '33'  => ['name' => 'France', 'min' => 9, 'max' => 9],
    '34'  => ['name' => 'Spain', 'min' => 9, 'max' => 9],
    '36'  => ['name' => 'Hungary', 'min' => 9, 'max' => 9],
    '39'  => ['name' => 'Italy', 'min' => 9, 'max' => 10],
    '40'  => ['name' => 'Romania', 'min' => 9, 'max' => 9],
    '41'  => ['name' => 'Switzerland', 'min' => 9, 'max' => 9],
    '43'  => ['name' => 'Austria', 'min' => 10, 'max' => 13],
    '44'  => ['name' => 'United Kingdom', 'min' => 10, 'max' => 10],
    '45'  => ['name' => 'Denmark', 'min' => 8, 'max' => 8],
    '46'  => ['name' => 'Sweden', 'min' => 7, 'max' => 10],
    '47'  => ['name' => 'Norway', 'min' => 8, 'max' => 8],
    '48'  => ['name' => 'Poland', 'min' => 9, 'max' => 9],
    '49'  => ['name' => 'Germany', 'min' => 10, 'max' => 11],
    '51'  => ['name' => 'Peru', 'min' => 9, 'max' => 9],
    '52'  => ['name' => 'Mexico', 'min' => 10, 'max' => 10],
    '53'  => ['name' => 'Cuba', 'min' => 8, 'max' => 8],
    '54'  => ['name' => 'Argentina', 'min' => 10, 'max' => 10],
    '55'  => ['name' => 'Brazil', 'min' => 10, 'max' => 11],
    '56'  => ['name' => 'Chile', 'min' => 9, 'max' => 9],
    '57'  => ['name' => 'Colombia', 'min' => 10, 'max' => 10],
    '58'  => ['name' => 'Venezuela', 'min' => 10, 'max' => 10],
    '60'  => ['name' => 'Malaysia', 'min' => 9, 'max' => 10],
    '61'  => ['name' => 'Australia', 'min' => 9, 'max' => 9],
    '62'  => ['name' => 'Indonesia', 'min' => 9, 'max' => 12],
    '63'  => ['name' => 'Philippines', 'min' => 10, 'max' => 10],
    '64'  => ['name' => 'New Zealand', 'min' => 8, 'max' => 10],
    '65'  => ['name' => 'Singapore', 'min' => 8, 'max' => 8],
    '66'  => ['name' => 'Thailand', 'min' => 9, 'max' => 9],
    '81'  => ['name' => 'Japan', 'min' => 10, 'max' => 11],
    '82'  => ['name' => 'South Korea', 'min' => 9, 'max' => 10],
    '84'  => ['name' => 'Vietnam', 'min' => 9, 'max' => 10],
    '86'  => ['name' => 'China', 'min' => 11, 'max' => 11],
    '90'  => ['name' => 'Turkey', 'min' => 10, 'max' => 10],
    '91'  => ['name' => 'India', 'min' => 10, 'max' => 10],
    '92'  => ['name' => 'Pakistan', 'min' => 10, 'max' => 10],
    '93'  => ['name' => 'Afghanistan', 'min' => 9, 'max' => 9],
    '94'  => ['name' => 'Sri Lanka', 'min' => 9, 'max' => 9],
    '95'  => ['name' => 'Myanmar', 'min' => 8, 'max' => 10],
    '98'  => ['name' => 'Iran', 'min' => 10, 'max' => 10],
    '212' => ['name' => 'Morocco', 'min' => 9, 'max' => 9],
    '213' => ['name' => 'Algeria', 'min' => 9, 'max' => 9],
    '216' => ['name' => 'Tunisia', 'min' => 8, 'max' => 8],
    '218' => ['name' => 'Libya', 'min' => 9, 'max' => 9],
    '220' => ['name' => 'Gambia', 'min' => 7, 'max' => 7],
    '221' => ['name' => 'Senegal', 'min' => 9, 'max' => 9],
    '223' => ['name' => 'Mali', 'min' => 8, 'max' => 8],
    '224' => ['name' => 'Guinea', 'min' => 9, 'max' => 9],
    '225' => ['name' => 'Ivory Coast', 'min' => 10, 'max' => 10],
    '226' => ['name' => 'Burkina Faso', 'min' => 8, 'max' => 8],
    '227' => ['name' => 'Niger', 'min' => 8, 'max' => 8],
    '228' => ['name' => 'Togo', 'min' => 8, 'max' => 8],
    '229' => ['name' => 'Benin', 'min' => 8, 'max' => 8],
    '230' => ['name' => 'Mauritius', 'min' => 8, 'max' => 8],
    '231' => ['name' => 'Liberia', 'min' => 7, 'max' => 9],
    '232' => ['name' => 'Sierra Leone', 'min' => 8, 'max' => 8],
    '233' => ['name' => 'Ghana', 'min' => 9, 'max' => 9],
    '234' => ['name' => 'Nigeria', 'min' => 10, 'max' => 10],
    '235' => ['name' => 'Chad', 'min' => 8, 'max' => 8],
    '236' => ['name' => 'Central African Republic', 'min' => 8, 'max' => 8],
    '237' => ['name' => 'Cameroon', 'min' => 9, 'max' => 9],
    '238' => ['name' => 'Cape Verde', 'min' => 7, 'max' => 7],
    '239' => ['name' => 'São Tomé and Príncipe', 'min' => 7, 'max' => 7],
    '240' => ['name' => 'Equatorial Guinea', 'min' => 9, 'max' => 9],
    '241' => ['name' => 'Gabon', 'min' => 8, 'max' => 8],
    '242' => ['name' => 'Republic of the Congo', 'min' => 9, 'max' => 9],
    '243' => ['name' => 'DR Congo', 'min' => 9, 'max' => 9],
    '244' => ['name' => 'Angola', 'min' => 9, 'max' => 9],
    '245' => ['name' => 'Guinea-Bissau', 'min' => 7, 'max' => 7],
    '246' => ['name' => 'British Indian Ocean Territory', 'min' => 7, 'max' => 7],
    '248' => ['name' => 'Seychelles', 'min' => 7, 'max' => 7],
    '249' => ['name' => 'Sudan', 'min' => 9, 'max' => 9],
    '250' => ['name' => 'Rwanda', 'min' => 9, 'max' => 9],
    '251' => ['name' => 'Ethiopia', 'min' => 9, 'max' => 9],
    '252' => ['name' => 'Somalia', 'min' => 8, 'max' => 9],
    '253' => ['name' => 'Djibouti', 'min' => 8, 'max' => 8],
    '254' => ['name' => 'Kenya', 'min' => 9, 'max' => 9],
    '255' => ['name' => 'Tanzania', 'min' => 9, 'max' => 9],
    '256' => ['name' => 'Uganda', 'min' => 9, 'max' => 9],
    '257' => ['name' => 'Burundi', 'min' => 8, 'max' => 8],
    '258' => ['name' => 'Mozambique', 'min' => 9, 'max' => 9],
    '260' => ['name' => 'Zambia', 'min' => 9, 'max' => 9],
    '261' => ['name' => 'Madagascar', 'min' => 9, 'max' => 9],
    '263' => ['name' => 'Zimbabwe', 'min' => 9, 'max' => 9],
    '264' => ['name' => 'Namibia', 'min' => 9, 'max' => 9],
    '265' => ['name' => 'Malawi', 'min' => 9, 'max' => 9],
    '266' => ['name' => 'Lesotho', 'min' => 8, 'max' => 8],
    '267' => ['name' => 'Botswana', 'min' => 8, 'max' => 8],
    '268' => ['name' => 'Eswatini', 'min' => 8, 'max' => 8],
    '269' => ['name' => 'Comoros', 'min' => 7, 'max' => 7],
    '352' => ['name' => 'Luxembourg', 'min' => 9, 'max' => 9],
    '353' => ['name' => 'Ireland', 'min' => 9, 'max' => 9],
    '354' => ['name' => 'Iceland', 'min' => 7, 'max' => 9],
    '355' => ['name' => 'Albania', 'min' => 9, 'max' => 9],
    '356' => ['name' => 'Malta', 'min' => 8, 'max' => 8],
    '357' => ['name' => 'Cyprus', 'min' => 8, 'max' => 8],
    '358' => ['name' => 'Finland', 'min' => 9, 'max' => 10],
    '359' => ['name' => 'Bulgaria', 'min' => 8, 'max' => 9],
    '370' => ['name' => 'Lithuania', 'min' => 8, 'max' => 8],
    '371' => ['name' => 'Latvia', 'min' => 8, 'max' => 8],
    '372' => ['name' => 'Estonia', 'min' => 7, 'max' => 8],
    '373' => ['name' => 'Moldova', 'min' => 8, 'max' => 8],
    '374' => ['name' => 'Armenia', 'min' => 8, 'max' => 8],
    '375' => ['name' => 'Belarus', 'min' => 9, 'max' => 9],
    '376' => ['name' => 'Andorra', 'min' => 6, 'max' => 9],
    '377' => ['name' => 'Monaco', 'min' => 8, 'max' => 8],
    '378' => ['name' => 'San Marino', 'min' => 10, 'max' => 10],
    '380' => ['name' => 'Ukraine', 'min' => 9, 'max' => 9],
    '381' => ['name' => 'Serbia', 'min' => 8, 'max' => 9],
    '382' => ['name' => 'Montenegro', 'min' => 8, 'max' => 8],
    '383' => ['name' => 'Kosovo', 'min' => 8, 'max' => 8],
    '385' => ['name' => 'Croatia', 'min' => 8, 'max' => 9],
    '386' => ['name' => 'Slovenia', 'min' => 8, 'max' => 8],
    '387' => ['name' => 'Bosnia and Herzegovina', 'min' => 8, 'max' => 8],
    '389' => ['name' => 'North Macedonia', 'min' => 8, 'max' => 8],
    '420' => ['name' => 'Czech Republic', 'min' => 9, 'max' => 9],
    '421' => ['name' => 'Slovakia', 'min' => 9, 'max' => 9],
    '423' => ['name' => 'Liechtenstein', 'min' => 7, 'max' => 9],
    '852' => ['name' => 'Hong Kong', 'min' => 8, 'max' => 8],
    '853' => ['name' => 'Macau', 'min' => 8, 'max' => 8],
    '855' => ['name' => 'Cambodia', 'min' => 8, 'max' => 9],
    '856' => ['name' => 'Laos', 'min' => 8, 'max' => 10],
    '880' => ['name' => 'Bangladesh', 'min' => 10, 'max' => 10],
    '886' => ['name' => 'Taiwan', 'min' => 9, 'max' => 9],
    '960' => ['name' => 'Maldives', 'min' => 7, 'max' => 7],
    '961' => ['name' => 'Lebanon', 'min' => 7, 'max' => 8],
    '962' => ['name' => 'Jordan', 'min' => 9, 'max' => 9],
    '963' => ['name' => 'Syria', 'min' => 9, 'max' => 9],
    '964' => ['name' => 'Iraq', 'min' => 10, 'max' => 10],
    '965' => ['name' => 'Kuwait', 'min' => 8, 'max' => 8],
    '966' => ['name' => 'Saudi Arabia', 'min' => 9, 'max' => 9],
    '967' => ['name' => 'Yemen', 'min' => 9, 'max' => 9],
    '968' => ['name' => 'Oman', 'min' => 8, 'max' => 8],
    '970' => ['name' => 'Palestine', 'min' => 9, 'max' => 9],
    '971' => ['name' => 'United Arab Emirates', 'min' => 9, 'max' => 9],
    '972' => ['name' => 'Israel', 'min' => 9, 'max' => 9],
    '973' => ['name' => 'Bahrain', 'min' => 8, 'max' => 8],
    '974' => ['name' => 'Qatar', 'min' => 8, 'max' => 8],
    '975' => ['name' => 'Bhutan', 'min' => 8, 'max' => 8],
    '976' => ['name' => 'Mongolia', 'min' => 8, 'max' => 8],
    '977' => ['name' => 'Nepal', 'min' => 10, 'max' => 10],
    '992' => ['name' => 'Tajikistan', 'min' => 9, 'max' => 9],
    '993' => ['name' => 'Turkmenistan', 'min' => 8, 'max' => 8],
    '994' => ['name' => 'Azerbaijan', 'min' => 9, 'max' => 9],
    '995' => ['name' => 'Georgia', 'min' => 9, 'max' => 9],
    '996' => ['name' => 'Kyrgyzstan', 'min' => 9, 'max' => 9],
    '998' => ['name' => 'Uzbekistan', 'min' => 9, 'max' => 9],
];